[build]
  publish = "exampleSite/public"
  command = "hugo -s exampleSite"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_THEMESDIR = "/opt/build"
  HUGO_VERSION = "0.66.0"

[context.production.environment]
 HUGO_BASEURL = "https://workshop-serverless-amplify.vercel.app/"


[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"
